<?php

use App\Livewire\BangGia;
use App\Livewire\KhoGiaoDien;
use App\Livewire\Mau1;
use App\Livewire\Mau2;
use App\Livewire\Mau3;
use App\Livewire\Mau4;
use App\Livewire\Mau5;
use App\Livewire\Mau6;
use App\Livewire\Mau7;
use App\Livewire\Mau8;
use App\Livewire\Mau9;
use App\Livewire\Mau10;
use App\Livewire\Mau11;
use App\Livewire\Mau12;
use App\Livewire\Mau13;
use App\Livewire\Mau14;
use App\Livewire\Mau15;
use App\Livewire\Mau16;
use App\Livewire\Mau17;
use App\Livewire\Mau18;
use App\Livewire\Mau19;
use App\Livewire\Mau20;
use App\Livewire\Mau21;
use App\Livewire\Mau22;
use App\Livewire\Mau23;
use App\Livewire\Mau24;
use App\Livewire\Mau25;
use App\Livewire\Mau26;
use App\Livewire\Mau27;
use App\Livewire\Mau28;
use App\Livewire\Mau29;
use App\Livewire\Mau30;
use App\Livewire\Mau31;
use App\Livewire\Mau32;
use App\Livewire\Mau33;
use App\Livewire\Mau34;
use App\Livewire\Mau35;
use App\Livewire\Mau36;
use App\Livewire\Mau37;
use App\Livewire\Mau38;
use App\Livewire\Mau39;
use App\Livewire\Mau40;
use App\Livewire\Mau41;
use App\Livewire\Mau42;
use App\Livewire\Mau43;
use App\Livewire\Mau44;

use App\Livewire\Detail\ChiTietMau1;
use App\Livewire\Detail\ChiTietMau2;
use App\Livewire\Detail\ChiTietMau3;
use App\Livewire\Detail\ChiTietMau4;
use App\Livewire\Detail\ChiTietMau5;
use App\Livewire\Detail\ChiTietMau6;
use App\Livewire\Detail\ChiTietMau7;
use App\Livewire\Detail\ChiTietMau8;
use App\Livewire\Detail\ChiTietMau9;
use App\Livewire\Detail\ChiTietMau10;
use App\Livewire\Detail\ChiTietMau11;
use App\Livewire\Detail\ChiTietMau12;
use App\Livewire\Detail\ChiTietMau13;
use App\Livewire\Detail\ChiTietMau14;
use App\Livewire\Detail\ChiTietMau15;
use App\Livewire\Detail\ChiTietMau16;
use App\Livewire\Detail\ChiTietMau17;
use App\Livewire\Detail\ChiTietMau18;
use App\Livewire\Detail\ChiTietMau19;
use App\Livewire\Detail\ChiTietMau20;
use App\Livewire\Detail\ChiTietMau21;
use App\Livewire\Detail\ChiTietMau22;
use App\Livewire\Detail\ChiTietMau23;
use App\Livewire\Detail\ChiTietMau24;
use App\Livewire\Detail\ChiTietMau25;
use App\Livewire\Detail\ChiTietMau26;
use App\Livewire\Detail\ChiTietMau27;
use App\Livewire\Detail\ChiTietMau28;
use App\Livewire\Detail\ChiTietMau29;
use App\Livewire\Detail\ChiTietMau30;
use App\Livewire\Detail\ChiTietMau31;
use App\Livewire\Detail\ChiTietMau32;
use App\Livewire\Detail\ChiTietMau33;
use App\Livewire\Detail\ChiTietMau34;
use App\Livewire\Detail\ChiTietMau35;
use App\Livewire\Detail\ChiTietMau36;
use App\Livewire\Detail\ChiTietMau37;
use App\Livewire\Detail\ChiTietMau38;
use App\Livewire\Detail\ChiTietMau39;
use App\Livewire\Detail\ChiTietMau40;
use App\Livewire\Detail\ChiTietMau41;
use App\Livewire\Detail\ChiTietMau42;
use App\Livewire\Detail\ChiTietMau43;
use App\Livewire\Detail\ChiTietMau44;
use App\Livewire\TrangChu;
use Illuminate\Support\Facades\Route;

// Route cho mau-1 đến mau-44
Route::get('/', TrangChu::class);
Route::get('/kho-giao-dien', KhoGiaoDien::class);
Route::get('/bang-gia', BangGia::class);
 
Route::get('/mau-1', Mau1::class);
Route::get('/mau-2', Mau2::class);
Route::get('/mau-3', Mau3::class);
Route::get('/mau-4', Mau4::class);
Route::get('/mau-5', Mau5::class);
Route::get('/mau-6', Mau6::class);
Route::get('/mau-7', Mau7::class);
Route::get('/mau-8', Mau8::class);
Route::get('/mau-9', Mau9::class);
Route::get('/mau-10', Mau10::class);
Route::get('/mau-11', Mau11::class);
Route::get('/mau-12', Mau12::class);
Route::get('/mau-13', Mau13::class);
Route::get('/mau-14', Mau14::class);

// Route::get('/mau-15', Mau15::class);
// Route::get('/mau-16', Mau16::class);
// Route::get('/mau-17', Mau17::class);
// Route::get('/mau-18', Mau18::class);
// Route::get('/mau-19', Mau19::class);
// Route::get('/mau-20', Mau20::class);
// Route::get('/mau-21', Mau21::class);
// Route::get('/mau-22', Mau22::class);
// Route::get('/mau-23', Mau23::class);
// Route::get('/mau-24', Mau24::class);
// Route::get('/mau-25', Mau25::class);
// Route::get('/mau-26', Mau26::class);
// Route::get('/mau-27', Mau27::class);
// Route::get('/mau-28', Mau28::class);
// Route::get('/mau-29', Mau29::class);

// Route::get('/mau-30', Mau30::class);
// Route::get('/mau-31', Mau31::class);
// Route::get('/mau-32', Mau32::class);
// Route::get('/mau-33', Mau33::class);
// Route::get('/mau-34', Mau34::class);
// Route::get('/mau-35', Mau35::class);
// Route::get('/mau-36', Mau36::class);
// Route::get('/mau-37', Mau37::class);
// Route::get('/mau-38', Mau38::class);
// Route::get('/mau-39', Mau39::class);
// Route::get('/mau-40', Mau40::class);
// Route::get('/mau-41', Mau41::class);
// Route::get('/mau-42', Mau42::class);
// Route::get('/mau-43', Mau43::class);
// Route::get('/mau-44', Mau44::class);

Route::get('/1/{code}', ChiTietMau1::class);
Route::get('/2/{code}', ChiTietMau2::class);
Route::get('/3/{code}', ChiTietMau3::class);
Route::get('/4/{code}', ChiTietMau4::class);
Route::get('/5/{code}', ChiTietMau5::class);
Route::get('/6/{code}', ChiTietMau6::class);
Route::get('/7/{code}', ChiTietMau7::class);
Route::get('/8/{code}', ChiTietMau8::class);
Route::get('/9/{code}', ChiTietMau9::class);
Route::get('/10/{code}', ChiTietMau10::class);
Route::get('/11/{code}', ChiTietMau11::class);
Route::get('/12/{code}', ChiTietMau12::class);
Route::get('/13/{code}', ChiTietMau13::class);
Route::get('/14/{code}', ChiTietMau14::class);
// Route::get('/15/{code}', ChiTietMau15::class);
// Route::get('/16/{code}', ChiTietMau16::class);
// Route::get('/17/{code}', ChiTietMau17::class);
// Route::get('/18/{code}', ChiTietMau18::class);
// Route::get('/19/{code}', ChiTietMau19::class);
// Route::get('/20/{code}', ChiTietMau20::class);
// Route::get('/21/{code}', ChiTietMau21::class);
// Route::get('/22/{code}', ChiTietMau22::class);
// Route::get('/23/{code}', ChiTietMau23::class);
// Route::get('/24/{code}', ChiTietMau24::class);
// Route::get('/25/{code}', ChiTietMau25::class);
// Route::get('/26/{code}', ChiTietMau26::class);
// Route::get('/27/{code}', ChiTietMau27::class);
// Route::get('/28/{code}', ChiTietMau28::class);
// Route::get('/29/{code}', ChiTietMau29::class);
// Route::get('/30/{code}', ChiTietMau30::class);
// Route::get('/31/{code}', ChiTietMau31::class);
// Route::get('/32/{code}', ChiTietMau32::class);
// Route::get('/33/{code}', ChiTietMau33::class);
// Route::get('/34/{code}', ChiTietMau34::class);
// Route::get('/35/{code}', ChiTietMau35::class);
// Route::get('/36/{code}', ChiTietMau36::class);
// Route::get('/37/{code}', ChiTietMau37::class);
// Route::get('/38/{code}', ChiTietMau38::class);
// Route::get('/39/{code}', ChiTietMau39::class);
// Route::get('/40/{code}', ChiTietMau40::class);
// Route::get('/41/{code}', ChiTietMau41::class);
// Route::get('/42/{code}', ChiTietMau42::class);
// Route::get('/43/{code}', ChiTietMau43::class);
// Route::get('/44/{code}', ChiTietMau44::class);